## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [34]:
import os
import numpy as np
import pandas as pd

In [35]:
# 設定 data_path
dir_data = './data/'

In [36]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

In [37]:
type(app_train)

pandas.core.frame.DataFrame

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [38]:
app_train.shape

(307511, 122)

In [39]:
app_train.index

RangeIndex(start=0, stop=307511, step=1)

In [40]:
idc = app_train.columns
idc

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 列出所有欄位

In [41]:
app_train.columns.values

array(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE',
       'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE',
       'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE',
       'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START',
       'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION',
       'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION',
       'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY',
       'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1',
       'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG',
       'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG',
       'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG',
       'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG',
       'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG',
       'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE',
       'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE',
       'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE',
       'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE',
       'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
       'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE',
       'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI',
       'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI',
       'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI',
       'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI',
       'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI',
       'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',
       'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE',
       'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE',
       'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE',
       'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3',
       'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6',
       'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9',
       'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12',
       'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15',
       'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18',
       'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21',
       'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype=object)

#### 截取部分資料

In [42]:
app_train.head(10)
lastH = app_train.iloc[:100,:20]
lastH.sort_values(by = "AMT_INCOME_TOTAL",ascending =False)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION
51,100059,0,Cash loans,M,Y,Y,1,540000.000,675000.0,34596.0,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.026392,-18632,-6977,-3904.0
59,100070,0,Cash loans,M,Y,Y,0,540000.000,1227901.5,46899.0,1129500.0,Unaccompanied,Working,Higher education,Widow,House / apartment,0.032561,-20544,-2091,-6846.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,Rented apartment,0.020713,-11146,-4306,-114.0
33,100039,0,Cash loans,M,Y,N,1,360000.000,733315.5,39069.0,679500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.015221,-11694,-2060,-3557.0
49,100056,0,Cash loans,M,Y,Y,0,360000.000,1506816.0,49927.5,1350000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010006,-18264,-9523,-5504.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,1530000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.003122,-18850,-449,-4597.0
58,100069,0,Cash loans,M,Y,Y,1,360000.000,640458.0,27265.5,517500.0,Unaccompanied,Working,Secondary / secondary special,Separated,House / apartment,0.007330,-14186,-1743,-2128.0
84,100099,0,Cash loans,F,N,Y,0,360000.000,733315.5,41076.0,679500.0,Unaccompanied,Pensioner,Secondary / secondary special,Separated,House / apartment,0.009175,-23032,365243,-9506.0
62,100073,0,Cash loans,M,Y,Y,0,324000.000,1130760.0,40189.5,810000.0,Unaccompanied,Pensioner,Higher education,Civil marriage,House / apartment,0.018850,-22843,365243,-1042.0
94,100112,1,Cash loans,M,Y,Y,0,315000.000,953460.0,64107.0,900000.0,Family,Commercial associate,Incomplete higher,Single / not married,With parents,0.030755,-10199,-2015,-4802.0
30,100035,0,Cash loans,F,N,Y,0,292500.000,665892.0,24592.5,477000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Civil marriage,House / apartment,0.025164,-15280,-2668,-5266.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,675000.0,Unaccompanied,State servant,Higher education,Single / not married,House / apartment,0.046220,-9994,-1796,-4668.0
98,100116,0,Cash loans,F,N,Y,0,243000.000,900000.0,32017.5,900000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.010006,-14751,-6737,-3390.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,697500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.016612,-14086,-3028,-643.0
53,100061,0,Cash loans,F,N,Y,2,225000.000,314055.0,16164.0,238500.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.006629,-10473,-1392,-2025.0
83,100098,0,Revolving loans,M,Y,N,0,225000.000,270000.0,13500.0,270000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.018850,-17390,-924,-7211.0
67,100079,0,Revolving loans,M,N,Y,0,225000.000,270000.0,13500.0,270000.0,Unaccompanied,Working,Secondary / secondary special,Separated,Municipal apartment,0.007330,-15359,-114,-5076.0
72,100084,0,Cash loans,M,N,Y,2,225000.000,495351.0,26140.5,459000.0,Unaccompanied,Working,Secondary / secondary special,Separated,House / apartment,0.024610,-14860,-1156,-23.0
86,100101,0,Cash loans,F,Y,Y,0,202500.000,343377.0,22072.5,283500.0,Unaccompanied,State servant,Higher education,Single / not married,House / apartment,0.072508,-18138,-969,-7421.0
85,100100,0,Cash loans,M,Y,Y,2,202500.000,796396.5,38443.5,643500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.008019,-15909,-1094,-3134.0
46,100053,0,Cash loans,F,N,Y,0,202500.000,305221.5,17649.0,252000.0,Family,Pensioner,Secondary / secondary special,Single / not married,House / apartment,0.019689,-20373,365243,-7760.0
44,100051,0,Cash loans,M,N,Y,0,202500.000,661702.5,48280.5,598500.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.007114,-9827,-758,-4166.0
41,100048,0,Cash loans,F,N,Y,0,202500.000,604152.0,29196.0,540000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.009175,-16971,-475,-3148.0
75,100087,0,Cash loans,F,N,Y,1,202500.000,1288350.0,37800.0,1125000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.003069,-17542,-2011,-1529.0
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0
40,100047,1,Cash loans,M,N,Y,0,202500.000,1193580.0,35028.0,855000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.025164,-17482,-1262,-1182.0
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,927000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.025164,-14815,-1652,-2299.0
36,100043,0,Cash loans,F,N,Y,2,198000.000,641173.5,23157.0,553500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.018850,-17199,-768,-63.0
90,100105,0,Cash loans,F,N,Y,0,193500.000,225000.0,23755.5,225000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-19810,-8862,-4493.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,100050,0,Cash loans,F,N,Y,0,108000.000,746280.0,42970.5,675000.0,Unaccompanied,Pensioner,Higher education,Single / not married,House / apartment,0.010966,-23548,365243,-5745.0
79,100094,0,Cash loans,F,N,Y,0,108000.000,113760.0,5301.0,90000.0,Unaccompanied,Pensioner,Higher education,Single / not married,House / apartment,0.030755,-22935,365243,-12623.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,387000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.018634,-12931,-1317,-6392.0
71,100083,0,Cash loans,M,Y,Y,0,103500.000,573628.5,24435.0,463500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.009657,-15406,-892,-341.0
47,100054,0,Cash loans,F,N,Y,0,99000.000,260640.0,26838.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.022625,-20121,-5332,-9197.0
38,100045,0,Cash loans,F,N,Y,0,99000.000,247275.0,17338.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.006207,-23920,365243,-9817.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,454500.0,"Spouse, partner",State servant,Secondary / secondary special,Married,House / apartment,0.035792,-16941,-1588,-4970.0
78,100093,0,Cash loans,F,N,Y,1,94500.000,585000.0,28273.5,585000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-18253,-721,-1701.0
89,100104,0,Cash loans,F,N,Y,0,90000.000,547344.0,30690.0,472500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.022625,-18556,-862,-6769.0
97,100115,0,Cash loans,F,N,N,0,90000.000,315000.0,14683.5,315000.0,"Spouse, partner",Working,Secondary / secondary special,Married,House / apartment,0.028663,-15371,-367,-3071.0
99,100118,0,Cash loans,F,N,Y,0,90000.000,675000.0,26541.0,675000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.026392,-22471,365243,-217.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,180000.0,Unaccompanied,Working,Higher education,Single / not married,With parents,0.030755,-10341,-1010,-4799.0
32,100037,0,Cash loans,F,N,N,0,90000.000,199008.0,20893.5,180000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.010032,-12974,-4404,-7123.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,454500.0,Unaccompanied,State servant,Higher education,Single / not married,House / apartment,0.015221,-11348,-2038,-1021.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,225000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-19334,-3494,-2419.0
45,100052,0,Revolving loans,F,N,Y,1,90000.000,180000.0,9000.0,180000.0,Family,Working,Secondary / secondary special,Civil marriage,House / apartment,0.009334,-7974,-895,-6591.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.006296,-24827,365243,-9012.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,270000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010966,-9776,-191,-4143.0
81,100096,1,Cash loans,F,N,Y,0,81000.000,252000.0,14593.5,252000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.028663,-24794,365243,-5391.0
54,100062,0,Cash loans,M,Y,N,0,81000.000,675000.0,32472.0,675000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.010006,-18611,365243,-6936.0
57,100068,0,Revolving loans,M,N,Y,0,81000.000,247500.0,12375.0,247500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-18248,-2351,-4375.0
52,100060,0,Cash loans,M,Y,N,0,76500.000,454500.0,14661.0,454500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-12282,-778,-1824.0
95,100113,0,Cash loans,M,Y,N,0,76500.000,135000.0,6696.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-15137,-7980,-9176.0
88,100103,0,Cash loans,F,N,Y,0,72000.000,450000.0,16965.0,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.009175,-21112,-1694,-6057.0
80,100095,0,Revolving loans,F,N,Y,2,67500.000,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.020246,-18693,-1434,-10255.0
56,100064,0,Cash loans,F,N,N,0,67500.000,298728.0,15381.0,202500.0,Family,Pensioner,Secondary / secondary special,Single / not married,Municipal apartment,0.019101,-21621,365243,-2019.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,67500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-13439,-2717,-311.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0
50,100058,0,Revolving loans,F,N,Y,0,54000.000,135000.0,6750.0,135000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.014520,-12406,-1176,-1149.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,135000.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.015221,-20417,365243,-5246.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子